### ISSUE TITLE
[23.09.2020]: UIDatePicker changed with iOS 14

### ISSUE THREAD

**Issue by mohadian** [karhoo/karhoo-ios-ui-sdk#24]
## Information

Device:

iOS version:
14.0
App Version:
1.2.5.

Environment:

Frequency (How often does the bug occur?):
Your picker now looks like this: 
![IMG_FB770DEDF8D9-1](https://user-images.githubusercontent.com/12498117/94002893-6af95880-fd92-11ea-8953-f587f7890548.jpeg)

You most likely want to set the style to wheels.
<img width="1495" alt="DatePickerViewController_xib" src="https://user-images.githubusercontent.com/12498117/94002912-6f257600-fd92-11ea-9188-2b8b3c976198.png">

Then it looks like this again:
![IMG_46AD6B35E309-1](https://user-images.githubusercontent.com/12498117/94002942-777db100-fd92-11ea-974a-fdb6278fea40.jpeg)

**Comment by JeevanThandi** [comment]
https://github.com/karhoo/karhoo-ios-ui-sdk/pull/25 [fix]
